baseURL = "/"
languageCode = "en-us"
title = "Mike Chester"
theme = "awesome-identity"
googleAnalytics = "UA-46220200-1"

[params.meta]
images = [ "/default.jpg" ]
description = "Software Development Engineer"

## Profile Configurations
[params.profile]
  portrait = "/default.jpg"
  firstname = "Mike"
  lastname = "Chester"
  title = "Software Development Engineer"
  bio = """
  10+ years of industry experience designing, developing, and testing business critical applications.
  """

[[params.contacts]]
  url = "mailto:mike@chester.io"
  icon = "fas fa-envelope"
[[params.contacts]]
  url = "https://linkedin.com/in/mchestr"
  icon = "fab fa-linkedin"
[[params.contacts]]
  url = "https://github.com/mchestr"
  icon = "fab fa-github"
[[params.contacts]]
  url = "https:/github.com/mchestr/home-cluster"
  icon = "fab fa-docker"

[[params.actions]]
  name = "Resume"
  url = "/resume.pdf"

