baseURL = "https://mchester.github.io"
languageCode = "en-us"
title = "Mike Chester"
theme = "awesome-identity"
googleAnalytics = "UA-46220200-1"

## Profile Configurations
[params.profile]
  portrait = "/default.jpeg"
  firstname = "Mike"
  lastname = "Chester"
  title = "Senior Full Stack Developer"
  bio = """
  8+ years of industry experience designing, developing, and testing business critical applications
  in a variety of programming languages.
  """

[params.contacts]
  email = "mikeachester@gmail.com"
  github = "mchestr"
  linkedin = "mchestr"

[[params.actions]]
  name = "Resume"
  url = "/resume.pdf"

